### ISSUE TITLE
Unchecked exception in render manager.

### ISSUE THREAD

**Issue by b26x** [ThatRedox/ChunkyClPlugin#20] opened 2021-11-30 17:47 UTC
When using the plugin the following error occurs:

Unchecked exception in render manager.
java.lang.ArrayIndexOutOfBoundsException: Index 65536 out of bounds for length 65536
	at chunkycl.GpuRayTracer.generateSky(GpuRayTracer.java:549)
	at chunkycl.AbstractOpenClRenderer.sceneReset(AbstractOpenClRenderer.java:38)
	at se.llbit.chunky.renderer.DefaultRenderManager.run(DefaultRenderManager.java:288)

**Comment by ThatRedox** [comment] 2022-01-28 04:04
Duplicate of #16.

**Closed by ThatRedox** 2022-01-28 04:04 UTC
